/**
 * @file Wizard-Konfiguration.
 */
export const WIZARD_CAT = {
    ethercat: ['ethercat'],
    sensor: ['sensor'],
    power: ['power', 'sonstiges'],
    oelflex: ['oelflex'],
    antrieb: ['power', 'sonstiges'],
    geber: ['sensor', 'power'],
    mts: ['power', 'sensor'],
    zuleitung: ['oelflex', 'sonstiges'],
    panel: ['ethercat', 'power']
};

export const DEFAULT_WIZARD_STEPS = [
    { id: '000-zuleitung', gruppe: '=000', frage: 'Zuleitung?', allowedCategories: WIZARD_CAT.zuleitung },
    { id: '000-kuehlgeraet', gruppe: '=000', frage: 'Kühlgerät?', allowedCategories: WIZARD_CAT.oelflex, bauteilTypen: ['kuehlgeraet', 'harting'], optional: true },
    { id: '004-ethercat-1', gruppe: '=004', frage: 'Reihenfolge EtherCAT Strang 1?', allowedCategories: WIZARD_CAT.ethercat, defaultCategory: 'ethercat' },
    { id: '004-ethercat-2', gruppe: '=004', frage: 'Reihenfolge EtherCAT Strang 2?', allowedCategories: WIZARD_CAT.ethercat, defaultCategory: 'ethercat' },
    { id: '004-ethercat-3', gruppe: '=004', frage: 'Reihenfolge EtherCAT Strang 3?', allowedCategories: WIZARD_CAT.ethercat, defaultCategory: 'ethercat' },
    { id: '005-panel-ipc', gruppe: '=005', frage: 'Panel und IPC?', allowedCategories: WIZARD_CAT.panel, defaultCategory: 'ethercat' },
    { id: '007-tuerschalter', gruppe: '=007', frage: 'Türschalter?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '007-lichtschranken', gruppe: '=007', frage: 'Lichtschranken?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '007-fussschalter', gruppe: '=007', frage: 'Fußschalter?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '007-zweihand', gruppe: '=007', frage: 'Zweihand Bedienpult?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '010-motorleitung', gruppe: '=010', frage: 'Motor, Regler und Motorleitung?', allowedCategories: WIZARD_CAT.antrieb, bauteilTypen: ['motor', 'regler'], defaultCategory: 'power' },
    { id: '010-geberleitung', gruppe: '=010', frage: 'Geberleitung?', allowedCategories: WIZARD_CAT.geber, defaultCategory: 'sensor' },
    { id: '011-bremsen', gruppe: '=011', frage: 'Bremsen, Sensorleitung?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '012-mts-power', gruppe: '=012', frage: 'MTS, Powerleitung?', allowedCategories: WIZARD_CAT.mts, defaultCategory: 'power' },
    { id: '013-dms', gruppe: '=013', frage: 'DMS Sensoren mit M12 Stecker?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '014-temp-tisch', gruppe: '=014', frage: 'Temperatursensor Tisch, Sensorleitung?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '014-temp-stoessel', gruppe: '=014', frage: 'Temperatursensor Stößel, Sensorleitung?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '016-nothalt', gruppe: '=016', frage: 'Not-Halt, Sensorleitung?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '018-vorschub', gruppe: '=018', frage: 'Vorschub (Motor, Regler, Leitungen)?', allowedCategories: ['power', 'sensor'], bauteilTypen: ['motor', 'regler'], defaultCategory: 'power' },
    { id: '020-motorleitung', gruppe: '=020', frage: 'Motor, Regler und Motorleitung?', allowedCategories: WIZARD_CAT.antrieb, bauteilTypen: ['motor', 'regler'], defaultCategory: 'power' },
    { id: '020-geberleitung', gruppe: '=020', frage: 'Geberleitung?', allowedCategories: WIZARD_CAT.geber, defaultCategory: 'sensor' },
    { id: '021-bremsen', gruppe: '=021', frage: 'Bremsen, Sensorleitung?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '022-mts-power', gruppe: '=022', frage: 'MTS, Powerleitung?', allowedCategories: WIZARD_CAT.mts, defaultCategory: 'power' },
    { id: '023-dms', gruppe: '=023', frage: 'DMS Sensoren mit M12 Stecker?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '024-temp-tisch', gruppe: '=024', frage: 'Temperatursensor Tisch, Sensorleitung?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '024-temp-stoessel', gruppe: '=024', frage: 'Temperatursensor Stößel, Sensorleitung?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '026-nothalt', gruppe: '=026', frage: 'Not-Halt, Sensorleitung?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '030-motorleitung', gruppe: '=030', frage: 'Motor, Regler und Motorleitung?', allowedCategories: WIZARD_CAT.antrieb, bauteilTypen: ['motor', 'regler'], defaultCategory: 'power' },
    { id: '030-geberleitung', gruppe: '=030', frage: 'Geberleitung?', allowedCategories: WIZARD_CAT.geber, defaultCategory: 'sensor' },
    { id: '031-bremsen', gruppe: '=031', frage: 'Bremsen, Sensorleitung?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '032-mts-power', gruppe: '=032', frage: 'MTS, Powerleitung?', allowedCategories: WIZARD_CAT.mts, defaultCategory: 'power' },
    { id: '033-dms', gruppe: '=033', frage: 'DMS Sensoren mit M12 Stecker?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '034-temp-tisch', gruppe: '=034', frage: 'Temperatursensor Tisch, Sensorleitung?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '034-temp-stoessel', gruppe: '=034', frage: 'Temperatursensor Stößel, Sensorleitung?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '036-nothalt', gruppe: '=036', frage: 'Not-Halt, Sensorleitung?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '040-motorleitung', gruppe: '=040', frage: 'Motor, Regler und Motorleitung?', allowedCategories: WIZARD_CAT.antrieb, bauteilTypen: ['motor', 'regler'], defaultCategory: 'power' },
    { id: '040-geberleitung', gruppe: '=040', frage: 'Geberleitung?', allowedCategories: WIZARD_CAT.geber, defaultCategory: 'sensor' },
    { id: '041-bremsen', gruppe: '=041', frage: 'Bremsen, Sensorleitung?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '042-mts-power', gruppe: '=042', frage: 'MTS, Powerleitung?', allowedCategories: WIZARD_CAT.mts, defaultCategory: 'power' },
    { id: '043-dms', gruppe: '=043', frage: 'DMS Sensoren mit M12 Stecker?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '044-temp-tisch', gruppe: '=044', frage: 'Temperatursensor Tisch, Sensorleitung?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '044-temp-stoessel', gruppe: '=044', frage: 'Temperatursensor Stößel, Sensorleitung?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '046-nothalt', gruppe: '=046', frage: 'Not-Halt, Sensorleitung?', allowedCategories: WIZARD_CAT.sensor, defaultCategory: 'sensor' },
    { id: '250-steckdosen', gruppe: '=250', frage: 'Steckdosen schalten (XS1/XS4)?', allowedCategories: WIZARD_CAT.oelflex, bauteilTypen: ['steckdose'], mengenfeld: { aktiv: true, label: 'Anzahl Steckdosen' }, optional: true, defaultCategory: 'oelflex' }
];
